In [1]:
import tensorflow as tf

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.8.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [7]:
print(result)


b'Hello World'


In [8]:
a = tf.constant(10)
b = tf.constant(20)

with tf.Session() as sess:
    res = sess.run(a + b)

In [9]:
print(res)

30


In [10]:
const = tf.constant(10)

In [11]:
fill_mat = tf.fill((4,4), 10)

In [12]:
with tf.Session() as sess:
    res = sess.run(fill_mat)
print(res)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [13]:
myzeroes = tf.zeros((4,4))
with tf.Session() as sess:
    res = sess.run(myzeroes)
print(res)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
myones = tf.ones((4,4))
with tf.Session() as sess:
    res = sess.run(myones)
print(res)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
normal_randoms = tf.random_normal((4,4))
with tf.Session() as sess:
    
    res = sess.run(normal_randoms)
print(res)

[[ 0.45634562  0.75029695  0.38767523  0.6431896 ]
 [ 0.85531026 -0.9137039   0.68136734  1.280846  ]
 [ 0.03918775  0.3564701   0.589538   -0.7222486 ]
 [ 0.3606149  -0.1068722   0.18077785 -0.89940625]]


In [16]:
uniform_randoms = tf.random_uniform((4,4), minval=0, maxval=1)
with tf.Session() as sess:
    res = sess.run(uniform_randoms)
print(res)

[[0.36967897 0.10019445 0.46331906 0.85332394]
 [0.58473253 0.06196344 0.03291047 0.6235423 ]
 [0.79829776 0.3118335  0.9143162  0.29278743]
 [0.7123059  0.27926373 0.586596   0.31606424]]


In [17]:
# cells after this will run with session active
sess = tf.InteractiveSession()
my_ops = [const, myzeroes, myones, normal_randoms, uniform_randoms ]

In [19]:
for op in my_ops:
    print(sess.run(op))

10
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-0.26192802  1.4063519   0.33376923  0.85462266]
 [-1.821814   -0.07031773  2.4945154   1.7663007 ]
 [ 2.27572     0.8339128   0.05238068 -0.2178611 ]
 [-1.1838872  -0.57662296 -0.86338586 -0.40015808]]
[[0.31400084 0.14886236 0.9631187  0.73890424]
 [0.53956234 0.3729285  0.65585864 0.02070916]
 [0.16591394 0.08334851 0.29438615 0.5461992 ]
 [0.832373   0.82953846 0.579021   0.29246974]]


In [20]:
a = tf.constant([ [1,2], [3,4] ])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [21]:
b = tf.constant([ [10], [100]])

In [22]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [23]:
res = tf.matmul(a,b)


In [24]:
sess.run(res)

array([[210],
       [430]], dtype=int32)