In [44]:
import tensorflow as tf

In [45]:
print(tf.__version__)

1.7.1


In [46]:
hello = tf.constant("Hello ")

In [47]:
world = tf.constant("World")

In [48]:
print(hello)

Tensor("Const_11:0", shape=(), dtype=string)


In [49]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [50]:
print(result)


b'Hello World'


In [51]:
a = tf.constant(10)
b = tf.constant(20)

with tf.Session() as sess:
    res = sess.run(a + b)

In [52]:
print(res)

30


In [53]:
const = tf.constant(10)

In [54]:
fill_mat = tf.fill((4,4), 10)

In [55]:
with tf.Session() as sess:
    res = sess.run(fill_mat)
print(res)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [56]:
myzeroes = tf.zeros((4,4))
with tf.Session() as sess:
    res = sess.run(myzeroes)
print(res)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [57]:
myones = tf.ones((4,4))
with tf.Session() as sess:
    res = sess.run(myones)
print(res)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [58]:
normal_randoms = tf.random_normal((4,4))
with tf.Session() as sess:
    
    res = sess.run(normal_randoms)
print(res)

[[-1.4060792e-01  1.0575157e+00  1.7626245e-01  7.5979531e-04]
 [-5.8559543e-01 -1.0615784e+00  5.2627099e-01 -8.3335346e-01]
 [ 2.7985245e-01 -1.1931949e+00 -3.1818357e-01 -5.7108521e-01]
 [ 3.4402674e-01  3.8516742e-01  6.5615928e-01  1.9380529e-01]]


In [59]:
uniform_randoms = tf.random_uniform((4,4), minval=0, maxval=1)
with tf.Session() as sess:
    res = sess.run(uniform_randoms)
print(res)

[[0.12464595 0.6789985  0.50096905 0.32997668]
 [0.24787712 0.3959248  0.25554454 0.68570375]
 [0.5421909  0.11039388 0.87776196 0.69085073]
 [0.75365424 0.7971027  0.9883541  0.2420119 ]]


In [60]:
# cells after this will run with session active
sess = tf.InteractiveSession()
my_ops = [const, myzeroes, myones, normal_randoms, uniform_randoms ]

In [61]:
for op in my_ops:
    print(sess.run(op))

10
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.36345276 -0.31102288 -0.07975826 -1.3227974 ]
 [ 1.630768    1.5551953  -0.04163273 -0.7404518 ]
 [ 0.19835897 -0.3440192  -0.8916227  -0.30974695]
 [ 0.05650728 -0.01787544 -0.26677772  0.334876  ]]
[[0.95890105 0.21326208 0.36324787 0.3335111 ]
 [0.44293237 0.14312398 0.4185865  0.9701394 ]
 [0.85085416 0.32227457 0.87501264 0.4504949 ]
 [0.60826945 0.5015508  0.58633506 0.1273992 ]]
